---
AWSTemplateFormatVersion: '2010-09-09'

Description: IAM Policies, and SageMaker Notebook to work with Fraud Detector.

Parameters:

  Uid:
    Type: String

Resources:
  # SageMaker Execution Role
  SageMakerIamRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonSageMakerFullAccess"
        - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
        - "arn:aws:iam::aws:policy/AmazonFraudDetectorFullAccessPolicy"
        - "arn:aws:iam::aws:policy/IAMFullAccess"

  # SageMaker notebook
  NotebookInstance:
    Type: "AWS::SageMaker::NotebookInstance"
    Properties:
      InstanceType: "ml.t3.medium"
      NotebookInstanceName: !Sub ${Uid}-FraudDetectorDemo
      RoleArn: !GetAtt SageMakerIamRole.Arn
      DefaultCodeRepository: https://github.com/aws-samples/amazon-fraud-detector-bot-detection-demo.git

Outputs:
  NotebookInstanceId:
    Value: !Ref NotebookInstance